//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectsTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDegree
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int DegreeId { get; set; }
    
        public virtual Degree Degree { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
